### ISSUE TITLE
failed build quasi

### ISSUE THREAD

**Issue by degtyarev-dm** [erickt/rust-quasi#30]
➜  quasi git:(master) rustc --version
rustc 1.6.0
➜  quasi git:(master) cargo --version
cargo 0.8.0 (28a0cbb 2016-01-17)
➜  quasi git:(master) cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling quasi v0.4.0 (file:///tmp/quasi/quasi)
src/lib.rs:335:9: 335:17 error: macro undefined: 'panictry!'
src/lib.rs:335         panictry!(parser.parse_expr())
                       ^~~~~~~~
src/lib.rs:339:9: 339:17 error: macro undefined: 'panictry!'
src/lib.rs:339         panictry!(parser.parse_item())
                       ^~~~~~~~
src/lib.rs:343:9: 343:17 error: macro undefined: 'panictry!'
src/lib.rs:343         panictry!(parser.parse_pat())
                       ^~~~~~~~
src/lib.rs:347:9: 347:17 error: macro undefined: 'panictry!'
src/lib.rs:347         panictry!(parser.parse_arm())
                       ^~~~~~~~
src/lib.rs:351:9: 351:17 error: macro undefined: 'panictry!'
src/lib.rs:351         panictry!(parser.parse_ty())
                       ^~~~~~~~
src/lib.rs:355:5: 355:13 error: macro undefined: 'panictry!'
src/lib.rs:355     panictry!(parser.parse_stmt())
                   ^~~~~~~~
src/lib.rs:359:9: 359:17 error: macro undefined: 'panictry!'
src/lib.rs:359         panictry!(parser.parse_attribute(permit_inner))
                       ^~~~~~~~
error: aborting due to 7 previous errors
Could not compile `quasi`.

**Comment by octplane** [comment]
Also on nightly, with another error:

`rustc 1.8.0-nightly (ce4b75f25 2016-02-12)`

```
> cargo build
   Compiling quasi v0.5.0
/Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.5.0/src/lib.rs:317:9: 320:83 error: mismatched types:
 expected `syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::StmtKind>>`,
    found `syntax::codemap::Spanned<syntax::ast::StmtKind>`
(expected struct `syntax::ptr::P`,
    found struct `syntax::codemap::Spanned`) [E0308]
/Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.5.0/src/lib.rs:317         parse::parse_stmt_from_source_str("<quote expansion>".to_string(),
/Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.5.0/src/lib.rs:318                                           s,
/Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.5.0/src/lib.rs:319                                           self.cfg(),
/Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.5.0/src/lib.rs:320                                           self.parse_sess()).expect("parse error")
/Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.5.0/src/lib.rs:317:9: 320:83 help: run `rustc --explain E0308` to see a detailed explanation
<syntax macros>:5:13: 5:14 error: mismatched types:
 expected `core::option::Option<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::StmtKind>>>`,
    found `core::option::Option<syntax::codemap::Spanned<syntax::ast::StmtKind>>`
(expected struct `syntax::ptr::P`,
    found struct `syntax::codemap::Spanned`) [E0308]
<syntax macros>:5 Ok ( e ) => e , Err ( mut e ) => { e . emit (  ) ; panic ! ( FatalError ) ; }
                              ^
/Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.5.0/src/lib.rs:359:5: 359:35 note: in this expansion of panictry! (defined in <syntax macros>)
<syntax macros>:5:13: 5:14 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 2 previous errors
Could not compile `quasi`.
```

**Comment by SethDusek** [comment]
Also having trouble building on newer version https://travis-ci.org/SethDusek/define-rust/builds/108925702

**Comment by KodrAus** [comment]
I'm not getting any issues on `nightly 2016-02-13`

**Comment by erickt** [comment]
Quasi 0.5 only worked on the nightly that came out two days ago, and was broken in yesterday's nightly. Quasi 0.6 should work though.
