### ISSUE TITLE
quasi doesn't compile anymore on Rust nightly

### ISSUE THREAD

**Issue by fabricedesre** [erickt/rust-quasi#31]
because of the changes from https://github.com/rust-lang/rust/pull/31487

**Comment by pczarn** [comment]
I'm starting to fix this

I think the cause is https://github.com/rust-lang/rust/pull/31583

**Comment by NikVolf** [comment]
keep us updated :)

**Comment by pczarn** [comment]
@Manishearth @erickt please review PRs.
