### ISSUE TITLE
quasi_codegen::expand() for non with-syntex builds

### ISSUE THREAD

**Issue by jdub** [erickt/rust-quasi#66]
There's currently no equivalent of `::expand()` for non `with-syntex` builds, which is a surprising API change. Would you like one? I'd probably add it without the extra stack as a starting point.

**Comment by dtolnay** [comment]
Sure, let's add one if you have a use case for it.

**Comment by jdub** [comment]
I'll close this one for you, because the `libbindgen` maintainers are more interested in moving to `quote` than maintaining `syntex`/`syntax` compatibility. Thanks!
